config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  resources :comments, only: [:create]
  # resources :articles do
  #   resources :comments, only: [:create]
  # end 
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :article
    
    validates :body, presence: true 
    validates :user_id, presence: true
    validates :article_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :delete_all
    has_many :comments
    validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]  
    end
    
    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert]= "You must be logged in to perform this action"
            redirect_to login_path
        end
    end
    # we just want to check if the user is logged in

end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # require "pry"
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: [:show, :edit] # restrict to login
  before_action :require_same_user, only: [:edit, :update, :destroy] # restrict only the owner of article can perform edit/update/delete

  
  def show
    @comment = Comment.new
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(params_article)
    @article.user = current_user # <--- Add this line
    if @article.save
      redirect_to @article
      # binding.pry
      flash[:notice] = 'Article was successfully created!'
    else
      render 'new'
    end
  end

  def update
    if @article.update(params_article)
      redirect_to @article
      flash[:notice] = 'Article was edited successfully!'
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.includes(:comments).find(params[:id])
  end

  def params_article
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert]= "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            @comments = Comment.where(article_id: @comment.article_id)
            respond_to do |format|
                format.js
            end
        end    
    end

    private

    def comment_params
      params.require(:comment).permit(:body, :article_id)
    end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:notice] = "Logged in successfully"
          redirect_to user
        else
          flash.now[:alert] = "There was something wrong with your login details"
          render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy] 

    def show
      @articles = @user.articles
    end

    def index
      @users = User.all
    end

    def new
        @user = User.new
    end

    def edit
    end
    
    def update
        if @user.update(user_params)
          flash[:notice] = "Your account information was successfully updated"
          redirect_to articles_path
        else
          render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id # We get code for login from session controller - and paste here
          # And instead of session[:user_id] = user.id we will use @user.id
          # That will sign the user in once they sign up
          flash[:notice] = "Welcome #{@user.username}, you have successfully signed up"
          redirect_to articles_path
        else
          render 'new'
        end
    end

    def destroy
      @user.destroy
      session[:user_id] = nil #otherwise app willl through an error
      flash.now[:alert] = "Account and all associated articles successfully deleted"
      render 'new'
      # redirect_to articles_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user
        flash[:alert]= "You can only edit your account"
        redirect_to @user
      end
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size=options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        # we want to return this url in an image tag
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
    end
    
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <div class="row row-cols-1 row-cols-md-2">
        <% @articles.each do |article| %>
            <div class="card mt-5 mx-auto shadow bg-white rounded" style="max-width: 20rem">
                <div class="card-header bg-light font-italic">
                    by <%= article.user.username if article.user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                    <a href="#"><%= link_to 'View', article_path(article), class: "btn btn-outline-success" %></a>
                    <% if logged_in? && article.user == current_user %>
                        <a href="#"><%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-warning" %></a>
                        <a href="#"><%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", method: :delete , data: {confirm: "Are you sure?"} %></a>
                    <% end %>
                </div>
                <div class="card-footer bg-light">
                    <small>
                    Created <%= time_ago_in_words(article.created_at) %> ago, 
                    edited <%= time_ago_in_words(article.updated_at) %> ago
                    </small>
                </div>
            </div>
        <% end %>
    </div>
</div>
<p><%= link_to 'Add new article', new_article_path %></p>

app/views/articles/_comments.html.erb
<div class="card">
    <% comments.each do |comment| %>
        <div class="comments card">
            <div class="card-body">
                <p class="card-title"><%= link_to comment.user.username, user_path(comment.user) %></p>
                <p class="card-text"><%= simple_format comment.body %></p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Added <%= time_ago_in_words(comment.created_at) %> ago</small>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
          <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article,class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-2 col-form-label text-white font-weight-bold" %><br/>
                    <div class="col-sm-10">
                    <%= f.text_field :title, class: 'form-control bg-white rounded', placeholder: "Title of article" %>
                    </div>
                </div>
                    
                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-white font-weight-bold" %><br/>
                    <div class="col-sm-10">
                    <%= f.text_area :description,rows: 10, class: 'form-control bg-white rounded', placeholder: "Description of article" %>
                    </div>
                </div>
                    
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-success" %> 
                </div>
            <% end %>

            <div class="form-group row justify-content-center">
                <%= link_to 'Return to Articles', articles_path, class: "btn btn-outline-secondary" %>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>
  

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
<h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && @article.user == current_user %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>    
  <h4>Comments</h4>
  <div id="post-comments">
    <%= render 'comments', comments: @article.comments %>
  </div>

  <h4 class="mt-3">Leave a comment</h4>
  <%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :article_id, value: @article.id %>
    <%= f.text_area :body, placeholder: "Your comment goes here" %>
    <%= f.submit "Submit comment", class: "btn btn-success" %>
  <% end %>
</div>

app/views/comments/create.js.erb
document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render 'articles/comments', comments: @comments) %>";

console.log("comment created....")

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Arbiona", "https://arbiona.herokuapp.com/", class: "text-white"  %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %> 
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= msg %> 
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Blog App", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers",users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>      
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column">
  
    <%= render 'layouts/navigation' %>
    <div id='page-content'>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the ABOUT page!</h1>


<%= link_to 'Articles page', articles_path %>
<%= link_to 'About page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron text-center">
        <h1 class="display-4">Blog App</h1>
        <p class="lead"> Does my blog need a tagline?</p>
        <hr class="my-4">
        <p>Top 50 remarkable campaign slogans for advertising.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>        
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">The Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? and user == current_user %>  
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>
<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>